---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: springbootmq
#        image: agilesolutions/demo:latest
        securityContext:
          runAsUser: 0
          privileged: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: PORT
            value : "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: demo
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  rules:
    - host: demo
      http:
        paths:
          - path: '/swagger'
            backend:
              serviceName: demo
              servicePort: http