apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  rules:
    - host: 'jenkins'
      http:
        paths:
          - path: '/'
            backend:
              serviceName: jenkins
              servicePort: http