apiVersion: skaffold/v1beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: agilesolutions/demo
      jibMaven: {}
deploy:
  kubectl:
    manifests:
      - ./app/*
      - ./mq/*
