apiVersion: skaffold/v1beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: agilesolutions/springbootmq
      jibMaven: {}
    - image: ibmcom/mq
      context: ./mq/
    - image: oracle/database:19.3.0-ee
      context: ./oracle/
# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - kubernetes/deployment.yml