---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oracle
  namespace: demo
  labels:
    app: oracle 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: oracle/database:latest
        securityContext:
          runAsUser: 0
          privileged: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1521
        - containerPort: 5500
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: PORT
            value : 1521
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-svc
  namespace: demo
  labels:
    app: oracle
spec:
  type: LoadBalancer
  ports:
  - port: 1521
    nodePort: 30082
  selector:
    app: demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oracle
  namespace: demo
  labels:
    app: oracle
spec:
  rules:
    - host: oracle
      http:
        paths:
          - path: '/'
            backend:
              serviceName: oracle
              servicePort: http