---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mq
  namespace: demo
  labels:
    app: mq 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: mq
#        image: ibmcom/mq:latest
        securityContext:
          runAsUser: 0
          privileged: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1414
        - containerPort: 9443
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: PORT
            value : "1414"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: demo
  labels:
    app: mq
spec:
  type: LoadBalancer
  ports:
  - port: 1414
    nodePort: 30081
  selector:
    app: demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mq
  namespace: demo
  labels:
    app: mq
spec:
  rules:
    - host: mq
      http:
        paths:
          - path: '/'
            backend:
              serviceName: mq
              servicePort: http