apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "jenkins"
  namespace: "jenkins"
  labels:
    chart: 'jenkins'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: "jenkins"
    spec:
#      securityContext:
#        runAsUser: 0
      containers:
      - name: "jenkins"
        image: "jenkins/jenkins:latest"
#        image: "jenkinsci/blueocean:latest"
        securityContext:
          runAsUser: 0
          privileged: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
#        volumeMounts:
#          -
#            mountPath: /var/run/docker.sock
#            name: "dockersock"
#            readOnly: false
        env:
          - name: PORT
            value : "8080"
#      volumes:
#      - name: dockersock
#        hostPath:
#          path: /var/run/docker.sock
#          type: File
