import java.text.SimpleDateFormat

pipeline {
  options {
    buildDiscarder logRotator(numToKeepStr: '5')
    disableConcurrentBuilds()
  }
  agent {
    kubernetes {
      cloud "kubernetes"
      label "prod"
      serviceAccount "build"
      yamlFile "../KubernetesPod.yaml"
    }      
  }
   parameters {
      string(name: 'Artifact', defaultValue: '', description: 'Specify artifact to be deployed')
      string(name: 'Version', defaultValue: '', description: 'Specify version to be deployed')
    }
   environment {
      cmAddr = "cm.host.com"
  }
  stages {
    stage("deploy") {
      when {
        branch "master"
      }
      steps {
        container("helm") {
        	script {
            	sh 'helm upgrade ../../charts/${params.artifact} --set image.tag=${params.version} --reuse-values '
        	}
        }
      }
    }
      post {
        failure {
          container("helm") {
        	script {
	            sh 'helm rollback ${params.artifact}'
			}
          }
        }
      }
    }
  }
}